version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  processpuzzle-logs:
    external: true

services:
  proxy:
    build: ./proxy
    image: zsuffazs/processpuzzle-proxy
    container_name: processpuzzle-proxy
    restart: always
    ports:
      - "8000:80"
    volumes:
      - processpuzzle-logs:/var/log/nginx
    networks:
      - prodnetwork
    depends_on:
      - processpuzzle-core

  processpuzzle-core:
    image: zsuffazs/processpuzzle-core
    container_name: processpuzzle-core
    restart: always
    ports:
      - "9125:9125"
    environment:
      - SPRING_PROFILES_ACTIVE: local
      - VIRTUAL_HOST: processpuzzle-core.local
    volumes:
      - processpuzzle-logs:/var/log/processpuzzle-core
    networks:
      - prodnetwork
    logging:
      driver: json-file